const mongoose = require('mongoose');


const EmpresaSchema = new mongoose.Schema({
  cnpj: String,
  valide: String,
  representante: String,
  razao_social: String,
  nome_fantasia: String,
  responsavel: String,
  utiliza: String,
  qt_consultas: Number,
  valor_vcm: Number,
  valor_consulta_un: Number,
  valor_concorrencia: Number,
  vcm_ofertado: Number,
  usa_pefin: String,
  utiliza_negativacao: String,
  valor_gasto_negativacao: Number,
  valor_pago_negativa: Number,
  ddd: String,
  telefone: String,
  ramal: Number,
  email: String,
  ddd2: String,
  telefone2: String,
  ramal2: Number,
  email2: String,
  observacao: String,
  localizar_cnpj: Number,
  data_primeiro_contato: String,
  hora: String,
  documento_consulta: String,
  percentagem_cnpj: Number,
  negociacao: String,
  data_ultimo_contrato: String,
  qt_que_negativa: Number,
  doc_negativado: String,
  percentagem_cnpj_negativa: Number,
  data_retorno: String,
  dias: Number,
  status_negociacao: String,
  status_venda: String,
  data_ultimo_contato: String,
  hora_ultimo_contato: String,
  endereco: String,
  cidade: String,
  uf: String,
});

module.exports = mongoose.model('Empresa', EmpresaSchema);